#!/usr/bin/bash

MANIM_RES_DIR="$HOME/Films/manim"
PODMAN_IMG_NAME="manim-img"

[ -e "$MANIM_RES_DIR" ] || {
    echo >&2 "[Info]  Creating default manim dir: $MANIM_RES_DIR"
    mkdir -p "$MANIM_RES_DIR"
}

podman images --noheading --format "{{ .Repository }}" "$PODMAN_IMG_NAME" | grep -q "/manim-img$"
[ $? -ne 0 ] && {
  echo >&2 "[Error] The $MANIM_RES_DIR podman image doesn't exist yet."
  echo >&2 "        Build it manually from the git repository."
  exit 1
}

echo >&2 "[Info]  Starting the manim..."
podman run -ti --rm --name mymanim \
    -v "$MANIM_RES_DIR:/output:Z" \
    -v "$PWD:/input:ro,Z" \
    -w "/input" \
    "$PODMAN_IMG_NAME" $@

